---
fixes:
  - |
    `FileTypeRouter` has a new parameter `raise_on_failure` with default value to `False`. When set to `True`, `FileNotFoundError` is always raised for non-existent files.
    Previously, this exception was raised only when processing a non-existent file and the `meta` parameter was provided to `run()`.
